[doc]
name = ' modern-tex-engines-automation-ai-latex-workshop-2023'
bundle = 'https://data1.fullyjustified.net/tlextras-2022.0r0.tar'

[[output]]
name = 'default'
index = 'default'
type = 'pdf'
shell_escape = true
